# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TravelHelper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TravelHelper

  target 'TravelHelperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TravelHelperUITests' do
    # Pods for testing
  end

  pod 'Firebase/Auth'

end
